Coding-Crew-Forever/Coding-Test-Study

.gitignore, julia8024/PGS_42578.py, julia8024/PGS_42586.py
> 환경 세팅 다시했음
<br>
[PGS] 의상 / Lv2 / 20분
[PGS] 기능 개발 / Lv2 / 20분
=> Julia8024/algorithm - first pull request

julia8024/PGS_12914.py, julia8024/PGS_12951.py, julia8024/PGS_12973.py, julia8024/PGS_131127.py, julia8024/PGS_138476.py, julia8024/PGS_154539.py, julia8024/PGS_42579.py, julia8024/PGS_42746.py, julia8024/PGS_42747.py, julia8024/PGS_43163.py
[PGS] 멀리뛰기 / Lv2 / 30분
[PGS] 단어 변환 / Lv3 / 2시간 `FLAG`
[PGS] 베스트앨범 / Lv3 / 40분 `FLAG`
[PGS] 귤 고르기 / Lv2 / 5분
[PGS] 할인 행사 /  Lv2 / 30분
[PGS] H-index / Lv2 / 20분
[PGS] 짝지어 제거하기 / Lv2 / 25분
[PGS] 가장 큰 수 / Lv2 / 20분
[PGS] JadenCase 문자열 만들기 / Lv2 / 20분
[PGS] 뒤에 있는 큰 수 찾기 / Lv2 / 1시간 10분 `FLAG`
<br>
>  `FLAG` : 나중에 다시 풀어보기
=> [2024년 3월 넷째주]Julia8024/algorithm

chaeryeon823/16953.py
_여러분 커밋 실수 죄송합니다.. 핳..._
1. [BOJ] 최소 힙 / 실버2
2. [BOJ] 최대 힙 / 실버2
3. [BOJ] 절댓값 힙 / 실버1
4. [BOJ] N번째 큰 수 / 실버2
5. [BOJ] 카드 합체 놀이 / 실버1
6. [BOJ] 강의실 배정 / 골드 5
<br>
> 우선순위큐를 사용해서 풀었습니다. 파이썬으로 우선순위 큐를 하는 방법도 공부해 보았습니다.
**PriorityQueue**
```python
from queue import PriorityQueue
q = PriorityQueue()
q = PriorityQueue(maxsize=10) # 크기 제한
q.put(3)
q.put(4)
q.put(1)
q1.put((1, 'apple')) # (우선순위, 값)의 형태로 저장할 수도 있음
q.get() # 1
q1.get()[1] # (우선순위, 값)의 형태에서 값 반환
```
<br>
**heapq**
```python
import heapq
hq = []
hq1 = [1, 2, 3]
heapq.heapify(arr)
heapq.heappush(hq, 4)
heapq.heappush(hq, 1)
heapq.heappush(hq, 3)
heapq.heappush(hq, 7)
heapq.heappop(hq)
heap_items = [1,3,5,7,9]
max_heap = []
for item in heap_items:
heapq.heappush(max_heap, (-item, item))
print(max_heap)
max_item = …
```
=> [2024년 3월 넷째주] chaeryeon823/algorithm

julia8024/PGS_12953.py, julia8024/PGS_131704.py
[PGS] N개의 최소공배수 / Lv2 / 10분
[PGS] 택배상자 / Lv2 / 15분
=> [2024년 4월 첫째주] julia8024/algorithm

julia8024/PGS_154538.py
[PGS] 숫자 변환하기 / Lv2 / 20분
> 나중에 다시 풀어보기
=> [2024년 4월 둘째주] julia8024/algorithm

julia8024/PGS_42842.py
[PGS] 카펫 / Lv2 / 15분
> 노랑 중앙에 갈색 테두리 한줄만 알면 풀리는 문제였음
> 노랑의 약수를 구하고, 큰 수가 너비가 되어야함
> 갈색 = (노랑너비 + 노랑높이)*2 + 4
=> [2024년 4월 셋째주] julia8024/algorithm

julia8024/PGS_42885.py
[PGS] 구명보트 / Lv2 / 30분
> 생각보다 오래걸림...
> 나중에 다시 시도해보기
=> [2024년 4월 넷째주] julia8024/algorithm

julia8024/PGS_132265.py
[PGS] 롤케이크 자르기 / Lv2 / 20분
> 문제 이해하는데에 조금 오래걸림,,,
=> [2024년 5월 첫째주] julia8024/algorithm

julia8024/PGS_12945.py
=> [2024년 5월 셋째주] julia8024/algorithm

julia8024/PGS_42883.py
=> [2024년 5월 넷째주] julia8024/algorithm

julia8024/PGS_ 64065.py
[PGS] 튜플 / Lv2 / 20분
> 우선 문자열을 리스트형태로 정제해주고, 각 리스트의 길이가 짧은 것부터 정렬
> 리스트의 각 요소가 answer에 없으면 넣고, 있으면 넘어감
> 
> 문제 읽을 때 어려워보였는데 입출력 이해하니까 어떻게 풀어야할지 감이 잡혔던 꽤나 쉬운 문제
> 더 깔끔하게 코드 짤 수 있을 것 같은데, 나중에 다시 풀어보면 좋을 듯
=> [2024년 6월 둘째주] julia8024/algorithm

ahma0/PGS_84512.java
=> [2024년 6월 셋째주] ahma0/algorithm

julia8024/PGS_ 84512.py
[PGS] 모음사전 / Lv2 / 20분
> 문제 노려보는데 10분 넘게 쓴듯
> 경우의 수로 풀었는데, 다른 사람들의 풀이 보니까 광기가 미쳤는데,,
=> [2024년 6월 셋째주] julia8024/algorithm

chaeryeon823/BOJ_1003.js
js로 처음 문제를 풀어봤어요.ㅠㅠ 
코테 js 는 너무 어렵네요
=> [2024년 6월 셋째주] chaeryeon823/algorithm

hh830/BOJ_14888.java
=> [2024년 6월 셋째주] hh830/algorithm

julia8024/PGS_ 12981.py
[PGS] 영어 끝말잇기 / Lv2 / 10분
https://school.programmers.co.kr/learn/courses/30/lessons/12981
=> [2024년 6월 넷째주] julia8024/algorithm

chaeryeon823/PGS_12939.js
파이썬으로 풀었던 lv2 문제들을 자바스크립트로 풀어보고 있습니다..
=> [2024년 6월 넷째주] chaechae823/algorithm

julia8024/PGS_12913.py
[PGS] 땅따먹기 / Lv2 / 15분
https://school.programmers.co.kr/learn/courses/30/lessons/12913
=> [2024년 7월 첫째주] julia8024/algorithm

julia8024/PGS_76502.py
[PGS] 괄호 회전하기 / Lv.2 / 15분
https://school.programmers.co.kr/learn/courses/30/lessons/76502
> deque로 풀었음
> 일반 stack 문제처럼 "[", "{", "(" 를 stack에 넣어두고 하나씩 꺼내보면서 비교할까도 생각했는데
> "어차피 한쌍이면 replace 써도 되는거 아님?"이라는 생각에 시도해봤는데 되네요
=> [2024년 7월 둘째주] julia8024/algorithm

julia8024/PGS_42587.py
[PGS] 프로세스 / Lv2 / 30분
https://school.programmers.co.kr/learn/courses/30/lessons/42587
=> [2024년 7월 넷째주] julia8024/algorithm

hh830/BOJ_2493.java, hh830/BOJ_4485.java
=> [2024년 8월 셋째주] hh830/algorithm

julia8024/PGS_87946.py
[PGS] 피로도 / Lv2 / 15분
https://school.programmers.co.kr/learn/courses/30/lessons/87946
> import permutations 해서 순열로 풀긴 했는데
> 푸는데 조금 헤맸음
=> [2024년 9월 다섯째주] julia8024/algorithm

julia8024/PGS_ 42748.js, julia8024/PGS_42746.js, julia8024/PGS_43162.js, julia8024/PGS_43165.js
코딩테스트 준비하느라 js로 풀었습니다...
파이썬만 하다가 js 하려니까 계속 세미콜론 빼먹어요 (머쓱)
=> [2024년 10월 첫째주] julia8024/algorithm

julia8024/PGS_161989.py, julia8024/PGS_42898.py, julia8024/PGS_43105.py
> 🗓️ 마감 기한 : 2025.01.12.(일)
> 🔥 제출일 : 2025.01.11.(토)
- [PGS] 덧칠하기 / Lv1 / 10분
- [PGS] 정수 삼각형 / Lv3 / 15분 ✨
- [PGS] 등굣길 / Lv3 / 15분 ✨
(✨ : DP 문제)
=> [2025년 1월 둘째주/julia8024] 다이나믹 프로그래밍 (Dynamic Programming)

hh830/BOJ_1010.java, hh830/BOJ_14940.java
🗓️ 마감 기한 : 2025.01.12.(일)
🔥 제출일 : 2025.01.12.(일)
풀이한 문제
[BOJ] 다리놓기 / 실버5 ✨
[BOJ] 쉬운 최단거리 / 실버1
(✨ : DP 문제)
=> [2025년 1월 둘째주/hh830] 다이나믹 프로그래밍 (Dynamic Programming)

julia8024/PGS_42748.py, julia8024/PGS_60057.py
> 🗓️ 마감 기한 : 2025.01.19.(일)
> 🔥 제출일 : 2025.01.19.(일)
- [PGS] 문자열 압축 / Lv2 / 30분
- [PGS] K번째수 / Lv1 / 5분 ✨
(✨ : 정렬 문제)
=> [2025년 1월 셋째주/julia8024] 정렬

chaeryeon823/PGS_17680.js, chaeryeon823/PGS_42746.js
=> [2025년 1월 셋째주/chaeryeon823] 정렬 

julia8024/PGS_43238.py
> 🗓️ 마감 기한 : 2025.01.26.(일)
> 🔥 제출일 : 2025.01.26.(일)
- [PGS] 입국심사 / Lv3 / 20분 ✨
(✨ : 이진 탐색 문제)
=> [2025년 1월 넷째주/julia8024] 이진 탐색

chaeryeon823/BOJ_1920.js, chaeryeon823/PGS_86052.py
=> [2025년 1월 넷째주/chaeryeon823] 이진 탐색

hh830/BOJ_18115.java, hh830/PGS_43238.java
=> [2025년 1월 넷째주/hh830] 이진 탐색

julia8024/PGS_172927.py
> 🗓️ 마감 기한 : 2025.02.02.(일)
> 🔥 제출일 : 2025.02.02.(일)
- [PGS] 광물 캐기 / Lv2 / 20분 ✨
(✨ : 구현 문제)
=> [2025년 1월 다섯째주 / julia8024] 구현

chaeryeon823/PGS_131127.js
=> [2025년 1월 다섯째주 / chaeryeon823] 구현

youbbin/PGS_12982.py, youbbin/PGS_42862.java
=> [2025년 2월 첫째주 / youbbin] 그리디

chaeryeon823/BOJ_11403.js
🗓️ 마감 기한 : 2025.02.16.(일)
🔥 제출일 : 2025.02.16.(일)
풀이한 문제
[BOJ] 경로 찾기 / S! ✨
(✨ : 최단경로)
=> [2025년 2월 둘째주 / chaeryeon823] 최단 경로

julia8024/PGS_12978.py
> 🗓️ 마감 기한 : 2025.02.16.(일)
> 🔥 제출일 : 2025.02.17.(월)
- [PGS] 배달 / Lv2 / 20분 ✨
(✨ : 최단 경로 문제)
=> [2025년 2월 둘째주 / julia8024] 최단 경로

julia8024/PGS_1844.py
> 🗓️ 마감 기한 : 2025.02.23.(일)
> 🔥 제출일 : 2025.02.23.(일)
- [PGS] 게임 맵 최단거리 / Lv2 / 30분 ✨
(✨ : DFS/BFS 문제)
=> [2025년 2월 셋째주 / julia8024] DFS/BFS

hh830/BOJ_4963.java
=> [2025년 2월 셋째주 / hh830] DFS/BFS

chaeryeon823/PGS_43165.py
=> [2025년 2월 셋째주 / chaeryeon823] DFS/BFS

chaeryeon823/PGS_49189.js
> 🗓️ 마감 기한 : 2025.03.01.(일)
> 🔥 제출일 : 2025.03.01.(일)
- [PGS] 가장 먼 노드 / lv 3
=> [2025년 2월 넷째주 / chaechae823] 그래프

julia8024/PGS_49191.py
> 🗓️ 마감 기한 : 2025.03.02.(일)
> 🔥 제출일 : 2025.03.02.(일)
- [PGS] 순위 / Lv3 / 40분 ✨
(✨ : 그래프 문제)
=> [2025년 2월 넷째주 / julia8024] 그래프

julia8024/PGS_42895.py
> 🗓️ 마감 기한 : 2025.03.09.(일)
> 🔥 제출일 : 2025.03.08.(토)
- [PGS] N으로 표현 / Lv3 / 40분 ✨
(✨ : DP 문제)
=> [2025년 3월 첫째주 / julia8024] 다이나믹 프로그래밍

chaeryeon823/PGS_43105.py
> 🗓️ 마감 기한 : 2025.03.09.(일)
> 🔥 제출일 : 2025.03.09.(일)
- [PGS] 정수 삼각형 / Lv3 ✨
=> [2025년 3월 첫째주 / chaeryeon823] 다이나믹 프로그래밍

youbbin/PGS_43105.py
> 🗓️ 마감 기한 : 2025.03.09.(일) <br>
> 🔥 제출일 : 2025.03.09.(일)<br>
> ⭐️ 주제 문제 풀이 : ⭕️ <br>
- [PGS] 정수 삼각형 / Lv3 / 20분✨
=> [2025년 3월 첫째주 / youbbin] 다이나믹 프로그래밍

hh830/PGS_42898.java
[PGS] - 프로그래머스
> 🗓️ 마감 기한 : 2025.03.09.(Sun) <br>
> 🔥 제출일 : 2025.03.09.(Sun)<br>
> ⭐️ 주제 문제 풀이 : ⭕️  <br>
- [PGS] 등굣길 / Lv3 / 60분 ✨
(✨ : 다이나믹 프로그래밍)
=> [2025년 3월 첫째주 / hh830] 다이나믹 프로그래밍

youbbin/PGS_42748.py
> 🗓️ 마감 기한 : 2025.03.16.(일) <br>
> 🔥 제출일 : 2025.03.16.(일) <br>
> ⭐️ 주제 문제 풀이 : ⭕️ <br>
- [PGS] K번째수 / Lv1 / 5분 ✨
=> [2025년 3월 둘째주 / youbbin] 정렬

julia8024/PGS_17686.py
> 🗓️ 마감 기한 : 2025.03.16.(일)
> 🔥 제출일 : 2025.03.16.(일)
- [PGS] [3차] 파일명 정렬 / Lv2 / 20분 ✨
(✨ : 정렬 문제)
=> [2025년 3월 둘째주 / julia8024] 정렬

hh830/BOJ_11399.java
> 🗓️ 마감 기한 : 2025.03.16.(일) <br>
> 🔥 제출일 : 2025.03.16.(일)<br>
> ⭐️ 주제 문제 풀이 : ⭕️ <br>
- [BOJ] ATM / 실버4 / 10분 ✨
정렬
=> [2025년 3월 둘째주 / hh830] 정렬

chaeryeon823/PGS_42747.js, chaeryeon823/PGS_42747.py
> 🗓️ 마감 기한 : 2025.03.16.(일요일)
> 🔥 제출일 : 2025.03.16.(일요일)
- [PGS] H-index / Lv2 ✨
- 자바스크립트, 파이썬
=> [2025년 3월 둘째주 / chaeryeon823] 정렬

ahma0/PGS_42747.java
> 🗓️ 마감 기한 : 2025.03.16.(일)
> 🔥 제출일 : 2025.03.16.(일)
- [PGS] H-Index / lv2 / 5분 ✨
=> [2025년 3월 둘째주 / ahma0] 정렬

youbbin/PGS_142085.py
> 🗓️ 마감 기한 : 2025.03.23.(일) <br>
> 🔥 제출일 : 2025.03.23.(일) <br>
> ⭐️ 주제 문제 풀이 : ⭕️<br>
- [PGS] 디펜스 게임 / Lv2 / 20분 ✨
=> [2025년 3월 셋째주/youbbin] 이진탐색

chaeryeon823/BOJ_1654.js
> 🗓️ 마감 기한 : 2025.3.23
> 🔥 제출일 : 2025.3.23
- [BOJ] 랜선 자르기 / S2 ✨
=> [2025년 3월 셋째주/chaeryeon823] 이진탐색

hh830/BOJ_1654.java
> 🗓️ 마감 기한 : 2025.03.23.(일) <br>
> 🔥 제출일 : 2025.03.23.(일)<br>
> ⭐️ 주제 문제 풀이 : ⭕️ <br>
- [BOJ] 랜선 자르기 / 실버2 / 20분 ✨
=> [2025년 3월 셋째주/hh830] 이진탐색

ahma0/PGS_43236.java
> 🗓️ 마감 기한 : 2025.03.23.(일)
> 🔥 제출일 : 2025.03.23.(일)
- [PGS] 징검다리 / lv4 / 22분 ✨
=> [2025년 3월 셋째주 / ahma0] 이진탐색

julia8024/PGS_43236.py
> 🗓️ 마감 기한 : 2025.3.23.(일)<br>
> 🔥 제출일 : 2025.3.23.(일)<br>
- [PGS] 징검다리 / Lv4 / 1시간 ✨
=> [2025년 3월 셋째주 / julia8024] 이진탐색

youbbin/PGS_49993.py
> 🗓️ 마감 기한 : 2025.03.30.(일)
> 🔥 제출일 : 2025.03.30.(일)
- [PGS] 스킬트리 / Lv2 / 20분 ✨
=> [2025년 3월 넷째주/youbbin] 구현

chaeryeon823/PGS_76502.py
> 🗓️ 마감 기한 : 2025.03.30 (일요일)
> 🔥 제출일 : 2025.3.30 (일요일)
- [PGS] 괄호 회전하기 / Lv 2 ✨
=> [2025년 3월 넷째주/chaeryeon823] 구현

ahma0/BOJ_14503.java
https://www.acmicpc.net/problem/14503
> 🗓️ 마감 기한 : 2025.03.30.(일)
> 🔥 제출일 : 2025.03.30.(일)
- [BOJ] 로봇청소기 / 골드5 / 53분 ✨
=> [2025년 03월 넷째주 / ahma0] 구현

ahma0/BOJ_1439.java
https://www.acmicpc.net/problem/1439
> 🗓️ 마감 기한 : 2025.04.06.(일)
> 🔥 제출일 : 2025.04.06.(일)
- [BOJ] 뒤집기 / 실버5 / 9분 ✨
=> [2025년 4월 첫째주 / ahma0] 아무거나(백준 실버, 프로그래머스 lv2 이상)

hh830/BOJ_15787.java
> 🗓️ 마감 기한 : 2025.04.06.(일)
> 🔥 제출일 : 2025.04.06.(일)
- [BOJ] 기차가 어둠을 헤치고 은하수를 / 실버2 / 60분 ✨
=> [2025년 4월 첫째주 / hh830] 아무거나(백준 실버, 프로그래머스 lv2 이상)

youbbin/BOJ_14425.java
> 🗓️ 마감 기한 : 2025.04.06.(일)
> 🔥 제출일 : 2025.04.06.(일)
- [BOJ] 문자열 집합 / 실버4 / 15분 ✨
=> [2025년 4월 첫째주 / youbbin] 아무거나(백준 실버, 프로그래머스 lv2 이상)

chaeryeon823/PGS_87390.js
> 🗓️ 마감 기한 : 2025.04.06. (일요일)
> 🔥 제출일 : 2025.04.06. (일요일)
- [PGS] n^2 배열 자르기 / Lv 2 ✨
=> [2025년 4월 첫째주 / chaeryeon823] 아무거나(백준 실버, 프로그래머스 lv2 이상)

hh830/BOJ_1541.java
> 🗓️ 마감 기한 : 2025.04.13.(일)
> 🔥 제출일 : 2025.04.13.(일)
- [BOJ] 잃어버린 괄호 / 실버2 / 30분 ✨
=> [2025년 4월 둘째주 / hh830] 그리디

youbbin/PGS_42885.py
> 🗓️ 마감 기한 : 2024.04.13.(일)
> 🔥 제출일 : 2024.04.13.(일)
- [PGS] 구명보트 / Lv2 / 20분 ✨
=> [2025년 4월 둘째주 / youbbin] 그리디

ahma0/BOJ_1789.java
> 🗓️ 마감 기한 : 2025.04.13.(일)
> 🔥 제출일 : 2025.04.13.(일)
> ⭐️ 주제 문제 풀이 : ⭕️ / ❌
- [BOJ] 수들의 합 / 실버5 / 10분 ✨
=> [2025년 4월 둘째주 / ahma0] 그리디

julia8024/PGS_87694.py
> 🗓️ 마감 기한 : 2025.04.20.(일)
> 🔥 제출일 : 2025.04.20.(일)
- [PGS] 아이템 줍기 / Lv3 / 1시간 20분 ✨
(✨ : DFS/BFS 문제)
=> [2025년 4월 셋째주 / julia8024] DFS/BFS

hh830/BOJ_11725.java
> 🗓️ 마감 기한 : 2025.04.20.(일)
> 🔥 제출일 : 2025.04.20.(일)
- [BOJ] 트리의 부모 찾기 / 실버2 / 30분 ✨
=> [2025년 4월 셋째주 / hh830] DFS / BFS

youbbin/PGS_43165.py
> 🗓️ 마감 기한 : 2025.04.20.(일)
> 🔥 제출일 : 2025.04.20.(일)
- [PGS] 타켓 넘버 / Lv2 / 20분 ✨
=> [2025년 4월 셋째주 / youbbin] DFS / BFS

jiyoung1814/bj_bfs_word_translte.py
🗓️ 마감 기한 : 2025.04.20.(일)
🔥 제출일 : 2025.04.20.(일)
풀이한 문제
[BOJ] 단어변환 / 실버3 / 32분 ✨
=> [2025년 4월 셋째주 / jiyoung1814] DFS / BFS

chaeryeon823/BOJ_2606.js
> 🗓️ 마감 기한 : 2025.04.20. (일요일)
> 🔥 제출일 : 2025.04.20. (일요일)
- [BOJ] 바이러스 / S3✨
=> [2025년 4월 셋째주 / chaeryeon823] DFS / BFS

ahma0/BOJ_2583.java
> 🗓️ 마감 기한 : 2025.04.20.(일)
> 🔥 제출일 : 2025.04.20.(일)
- [BOJ] 영역 구하기 / 실버1 / 23분 ✨
=> [2025년 4월 셋째주 / ahma0] DFS / BFS

hh830/BOJ_2468.java
> 🗓️ 마감 기한 : 2025.04.27.(SUN)
> 🔥 제출일 : 2025.04.27.(SUN)
- [BOJ] 안전 영역 / 실버1 / 60분 ✨
=> [2025년 04월 셋째주 / hh830] 그래프 이론

youbbin/PGS_49189.py
> 🗓️ 마감 기한 : 2025.04.27.(일)
> 🔥 제출일 : 2025.04.27.(일)
- [PGS] 가장 먼 노드 / Lv3 / 60분 ✨
=> [2025년 04월 셋째주 / youbbin] 그래프 이론

ahma0/BOJ_1389.java
> 🗓️ 마감 기한 : 2025.04.27.(일)
> 🔥 제출일 : 2025.04.27.(일)
- [BOJ] 케빈 베이컨의 6단계 법칙 / 실버1 / 23분 ✨
=> [2025년 04월 셋째주 / ahma0] 그래프 이론

chaeryeon823/BOJ_1012.js
> 🗓️ 마감 기한 : 2025.04.27.(일요일)
> 🔥 제출일 : 2025.04.27.(일요일)
- [BOJ] 유기농 배추 / S2 ✨
=> [2025년 04월 셋째주 / chaeryeon823] 그래프 이론

youbbin/BOJ_1316.java
> 🗓️ 마감 기한 : 2025.05.04.(일)
> 🔥 제출일 : 2025.05.03.(토)
- [BOJ] 그룹 단어 체커 / 실버5 / 30분 ✨
=> [2025년 04월 다섯째주 / youbbin] 아무거나

chaeryeon823/PGS_138476.py
> 🗓️ 마감 기한 : 2025.05.04.(일요일)
> 🔥 제출일 : 2025.05.04.(일요일)
- [PGS] 귤 고르기 / Lv 2 ✨
=> [2025년 04월 다섯째주 / chaeryeon823] 아무거나

ahma0/BOJ_28278.java
> 🗓️ 마감 기한 : 2025.05.04.(일)
> 🔥 제출일 : 2025.05.04.(일)
- [BOJ] 스택 2 / 실버4 / 10분 ✨
=> [2025년 04월 다섯째주 / ahma0] 아무거나

hh830/BOJ_2193.java
> 🗓️ 마감 기한 : 2025.05.04.(일)
> 🔥 제출일 : 2025.05.04(일)
- [BOJ] 이친수 / 실버3 / 10분 ✨
=> [2025년 04월 다섯째주 / hh830] 아무거나

jiyoung1814/boj_graph_min_cost.py, jiyoung1814/boj_graph_min_spanning_tree.py
🗓️ 마감 기한 : 2025.05.04.(일)
🔥 제출일 : 2025.05.04(일)
풀이한 문제
[BOJ] 최소비용 구하기 / 골드5 / 30분 ✨
=> [2025년 04월 다섯째주 / jiyoung1814] 아무거나

julia8024/PGS_42584.py
> 🗓️ 마감 기한 : 2025.05.04.(일)
> 🔥 제출일 : 2025.05.04.(일)
- [PGS] 주식가격 / Lv2 / 30분
=> [2025년 4월 다섯째주 / julia8024] 아무거나

chaeryeon823/BOJ_9623.js
> 🗓️ 마감 기한 : 2025.05.11.(일요일)
> 🔥 제출일 : 2025.05.11.(일요일)
> ⭐️ 주제 문제 풀이 : ⭕️ / ❌
- [BOJ] BABBA / S5 ✨
=> [2025년 5월 둘째주 / chaeryeon823] 다이나믹 프로그래밍 

hh830/BOJ_11055.java
> 🗓️ 마감 기한 : 2025.05.11.(일)
> 🔥 제출일 : 2025.05.11.(일)
- [BOJ] 가장 큰 증가하는 부분 수열 / 실버2 / 30분 ✨
=> [2025년 5월 둘째주 / hh830] 다이나믹 프로그래밍

youbbin/BOJ_11055.py
> 🗓️ 마감 기한 : 2025.05.11.(일)
> 🔥 제출일 : 2025.05.11.(일)
- [BOJ] 가장 큰 증가하는 부분 수열 / 실버2 / 20분 ✨
=> [2025년 5월 둘째주 / youbbin] 다이나믹 프로그래밍 

julia8024/BOJ_9625.py
> 🗓️ 마감 기한 : 2025.05.11.(일)
> 🔥 제출일 : 2025.05.11.(일)
- [BOJ] BABBA / 실버5 / 15분 ✨
(✨ : 다이나믹 프로그래밍 문제)
=> [2025년 5월 둘째주 / julia8024] 다이나믹 프로그래밍

ahma0/BOJ_16395.java
> 🗓️ 마감 기한 : 2025.05.11.(일)
> 🔥 제출일 : 2025.05.11.(일)
- [BOJ] 파스칼의 삼각형 / 실버5 / 5분 ✨
=> [2025년 5월 둘째주 / ahma0] 다이나믹 프로그래밍

youbbin/BOJ_11651.py
> 🗓️ 마감 기한 : 2025.05.18(일)
> 🔥 제출일 : 2025.05.12(월)
- [BOJ] 좌표 정렬하기 2 / 실버5 / 5분 ✨
=> [2025년 5월 셋째주 / youbbin] 정렬

hh830/PGS_42747.java
> 🗓️ 마감 기한 : 2025.05.18.(일)
> 🔥 제출일 : 2025.05.18.(일)
- [PGS] H-Index / Lv2 / 30분 ✨
=> [2025년 5월 셋째주 / hh830] 정렬

chaeryeon823/BOJ_11399.js
> 🗓️ 마감 기한 : 2025.05.18.(일요일)
> 🔥 제출일 : 2025.05.18.(일요일)
-[BOJ] ATM /  S4✨
=> [2025년 5월 셋째주 / chaeryeon823] 정렬

jiyoung1814/boj_sorting_coordinate_compression.py
> 🗓️ 마감 기한 : 2025.05.18
> 🔥 제출일 : 2025.05.18
[BOJ] 좌표 압축/ 실버2 / 10분
=> [2025년 5월 셋째주 / jiyoung1814] 정렬

youbbin/PGS_43238.py
> 🗓️ 마감 기한 : 2025.05.25.(일)
> 🔥 제출일 : 2025.05.23.(금)
-[PGS] 입국심사 / Lv3 / 30분 ✨
=> [2025년 5월 넷째주 / youbbin] 이진 탐색

chaeryeon823/BOJ_1193.js
> 🗓️ 마감 기한 : 2025.06.01.(일요일)
> 🔥 제출일 : 2025.06.01.(일요일)
- [BOJ] 분수 찾기 / S5 ✨
=> [2025년 5월 넷째주 / chaeryeon823] 구현

julia8024/BOJ_1072.py, julia8024/PGS_12949.py
> 🗓️ 마감 기한 : 2025.06.01.(일)
> 🔥 제출일 : 2025.06.01.(일)
- [PGS] 행렬의 곱셈 / Lv2 / 40분 ✨(구현)
- [BOJ] 게임 / 실버3 / 20분 ✨(이진 탐색)
=> [2025년 5월 넷째주 / julia8024] 구현 (+ 5월 넷째주 이진 탐색)

julia8024/PGS_87390.py
> 🗓️ 마감 기한 : 2025.06.08.(일)
> 🔥 제출일 : 2025.06.08.(일)
- [PGS] n^2 배열 자르기 / Lv2 / 15분 ✨
(✨ : 아무거나 문제)
=> [2025년 6월 첫째주 / julia8024] 아무거나

ahma0/PGS_87390.java
> 🗓️ 마감 기한 : 2025.06.08.(일)
> 🔥 제출일 : 2025.06.08.(일)
- [PGS] n^2 배열 자르기 / Lv2 / 20분 ✨
(✨ : 아무거나 문제)
=> [2025년 6월 첫째주 / ahma0] 아무거나

youbbin/PGS_12949.py, youbbin/PGS_42746.py
> 🗓️ 마감 기한 : 2025.06.08.(일)
> 🔥 제출일 : 2025.06.08.(일)
- [PGS] 가장 큰 수 / Lv2 / 20분 ✨
=> [2025년 6월 첫째주 / youbbin] 아무거나 

hh830/BOJ_1946.py
> 🗓️ 마감 기한 : 2025.06.15.(일)
> 🔥 제출일 : 2025.06.15.(일)
- [BOJ] 신입 사원 / 실버1 / 30분 ✨
=> [2025년 6월 둘째주 / hh830] 그리디

ahma0/BOJ_5585.java
> 🗓️ 마감 기한 : 2025.06.15.(일)
> 🔥 제출일 : 2025.06.15.(일)
- [BOJ] 거스름돈 / 브론즈2 / 8분 ✨
=> [2025년 6월 둘째주 / ahma0] 그리디

ahma0/BOJ_16953.java
> 🗓️ 마감 기한 : 2025.06.22.(일)
> 🔥 제출일 : 2025.06.22.(일)
- [BOJ] A → B / 실버2 / 25분 ✨
=> [2025년 6월 셋째주 / ahma0] DFS/BFS

PGS_43165.cs
> 🗓️ 마감 기한 : 2025.06.22.(일)
> 🔥 제출일 : 2025.06.22.(일)
- [PGS] 타겟 넘버 / Lv2 / 30분 ✨
=> [2025년 6월 셋째주 / youbbin] DFS/BFS

chaeryeon823/BOJ_16953.js
> 🗓️ 마감 기한 : 2025.06.22.(일요일)
> 🔥 제출일 : 2025.06.22.(일요일)
- [BOJ] A->B / S2 ✨
=> [2025년 6월 셋째주 / chaeryeon823] DFS/BFS

julia8024/BOJ_1012.py
> 🗓️ 마감 기한 : 2025.03.02.(일)
> 🔥 제출일 : 2025.03.02.(일)
- [BOJ] 유기농 배추 / Lv2 / 40분 ✨
(✨ : 그래프 문제)
=> [2025년 6월 넷째주 / julia8024] 그래프 이론

hh830/BOJ_2644.java
> 🗓️ 마감 기한 : 2025.06.29.(일)
> 🔥 제출일 : 2025.06.29.(일)
- [BOJ] 촌수계산 / 실버2 / 20분 ✨
=> [2025년 6월 넷째주 / hh830] 그래프 이론

chaeryeon823/BOJ_1012.py
> 🗓️ 마감 기한 : 2025.06.29.(일요일)
> 🔥 제출일 : 2025.06.29.(일요일)
- [BOJ] 유기농 배추 / S2 ✨
=> [2025년 6월 넷째주 / chaeryeon823] 그래프 이론

jiyoung1814/boj_graph_old_people_need_friends.py
🗓️ 마감 기한 : 2025.06.29.(일)
🔥 제출일 : 2025.06.27.(금)
풀이한 문제
[BOJ] 헌내기는 친구가 필요해 / 실버2 / 19분 
=> [2025년 6월 넷째주 / jiyoung1814] 그래프 이론

julia8024/BOJ_9095.py
> 🗓️ 마감 기한 : 2025.07.06.(일)
> 🔥 제출일 : 2025.07.06.(일)
- [BOJ] 1,2,3 더하기 / 실버3 / 10분 ✨
(✨ : dp 문제)
=> [2025년 7월 첫째주 / julia8024] 다이나믹 프로그래밍

chaeryeon823/BOJ_1463.js
> 🗓️ 마감 기한 : 2025.07.06.(일요일)
> 🔥 제출일 : 2025.07.06.(일요일)
- [BOJ] 1로 만들기 / S3 ✨
=> [2025년 7월 첫째주 / chaeryeon823] 다이나믹 프로그래밍

hh830/BOJ_1699.java
> 🗓️ 마감 기한 : 2025.07.06.(일)
> 🔥 제출일 : 2025.07.06.(일)
- [BOJ] 제곱수의 합 / 실버2 / 30분 ✨
=> [2025년 7월 첫째주 / hh830] 다이나믹 프로그래밍

jiyoung1814/boj_sorting_sort_inside.py
🗓️ 마감 기한 : 2025.07.13.(일)
🔥 제출일 : 2025.07.13.(일)
풀이한 문제
[BOJ] 소트인사이드 / 실버5 / 15분
=> [2025년 7월 둘째주 / jiyoung1814] 정렬

hh830/BOJ_1026.java
> 🗓️ 마감 기한 : 2025.07.13.(일)
> 🔥 제출일 : 2025.07.13.(일)
- [BOJ] 보물 / 실버4 / 10분 ✨
=> [2025년 7월 둘째주 / hh830] 정렬

youbbin/PGS_42748.cs
> 🗓️ 마감 기한 : 2025.07.13.(일)
> 🔥 제출일 : 2025.07.13.(일)
- [PGS] K번째수 / Lv1 / 20분 ✨
=> [2025년 7월 둘째주 /youbbin] 정렬

chaeryeon823/BOJ_11650.js
> 🗓️ 마감 기한 : 2025.07.13.(일요일)
> 🔥 제출일 : 2025.07.13.(일요일)
- [BOJ] 좌표 정렬하기 / S5 ✨
=> [2025년 7월 둘째주 /chaeryeon823] 정렬

jiyoung1814/boj_bfs_baby_shark.py
> 🗓️ 마감 기한 : 2025.07.20.
> 🔥 제출일 : 2025.07.18.
> ⭐️ 주제 문제 풀이 : ❌
- [BOJ] 아기상어 / 골드3 / 60분
=> [2025년 7월 셋째주/jiyoung1814] 이진탐색

hh830/BOJ_2805.java
> 🗓️ 마감 기한 : 2025.07.20.(일)
> 🔥 제출일 : 2025.07.20.(일)
- [BOJ] 나무자르기 / 실버2 / 30분 ✨
=> [2025년 7월 셋째주 / hh830] 이진탐색

chaeryeon823/BOJ_2805.js
> 🗓️ 마감 기한 : 2025.07.20.(일요일)
> 🔥 제출일 : 2025.07.20.(일요일)
- [BOJ] 나무 자르기 / S2✨
=> [2025년 7월 셋째주 / chaeryeon823] 이진탐색

julia8024/BOJ_2805.py
> 🗓️ 마감 기한 : 2025.07.20.(일)
> 🔥 제출일 : 2025.07.20.(일)
- [BOJ] 나무 자르기 / 실버2 / 20분 ✨
(✨ : 이진탐색 문제)
=> [2025년 7월 셋째주 / julia8024] 이진탐색

chaeryeon823/BOJ_1018.js
> 🗓️ 마감 기한 : 2025.07.27.(일요일)
> 🔥 제출일 : 2025.07.27.(일요일)
- [BOJ] 체스판 다시 칠하기 / S4 ✨
=> [2025년 7월 넷째주/chaeryeon823] 구현

ahma0/BOJ_2440.java
> 🗓️ 마감 기한 : 2025.07.27.(일)
> 🔥 제출일 : 2025.07.27.(일)
- [BOJ] 별찍기-3 / 브론즈4 / 3분 ✨
=> [2025년 7월 넷째주 / ahma0] 구현

jiyoung1814/boj_11000_assignment_class.py
> 🗓️ 마감 기한 : 2025.08.01
> 🔥 제출일 : 2025.08.03
- [BOJ] 강의실 배정 / 골드5 / 20분 ✨
=> [2025 7월 다섯째주/jiyoung1814] 아무거나

chaeryeon823/BOJ_2941.js
> 🗓️ 마감 기한 : 2025.08.03.(일요일)
> 🔥 제출일 : 2025.08.03.(일요일)
- [BOJ] 크로아티아 알파벳 / S5 ✨
=> [2025 8월 첫째주/chaeryeon823] 아무거나

ahma0/BOJ_24313.java
> 🗓️ 마감 기한 : 2025.08.03
> 🔥 제출일 : 2025.08.03
- [BOJ] 알고리즘 수업 - 점근적 표기 1 / 실버5 / 10분 ✨
=> [2025 8월 첫째주 / ahma0] 아무거나

youbbin/PGS_42862.cs
> 🗓️ 마감 기한 : 2025.08.10.(일)
> 🔥 제출일 : 2025.08.07.(목)
- [PGS] 체육복 / Lv1 / 30분 ✨
=>  [2025년 8월 첫째주 / youbbin] 그리디

hh830/BOJ_11047.java
> 🗓️ 마감 기한 : 2025.08.10.(일)
> 🔥 제출일 : 2025.08.10.(일)
- [BOJ] 동전0 / 실버4 / 20분 ✨
=> [2025년 8월 첫째주 / hh830] 그리디

jiyoung1814/boj_1715_gready_sort_card.py
> 🗓️ 마감 기한 : 2025.08.10.
> 🔥 제출일 : 2025.08.10
- [BOJ] 카드 정렬하기 / 골드 4 / 20분 ✨
=> [2025년 8월 첫째주 / jiyoung1814] 그리디

jiyoung1814/boj_16173_dfs_jum_king_jelly.py
> 🗓️ 마감 기한 : 2025.08.14
> 🔥 제출일 : 2025.08.17
- [BOJ] 점프왕 쩰리 / 실버 4 / 20분 ✨
=> [2025년 08월 2째주 / jiyoung1814] DFS/BFS

hh830/BOJ_11403.java
> 🗓️ 마감 기한 : 2025.08.17.(일)
> 🔥 제출일 : 2025.08.17.(일)
- [BOJ] 경로찾기 / 실버1 / 50분 ✨
=> [2025년 8월 둘째주 / hh830] DFS/BFS

chaeryeon823/BOJ_1260.js
> 🗓️ 마감 기한 : 2025.08.17.(일요일)
> 🔥 제출일 : 2025.08.17.(일요일)
- [BOJ] DFS와BFS / S2 ✨
=> [2025년 8월 둘째주 / chaeryeon823] DFS/BFS

ahma0/BOJ_11123.java
> 🗓️ 마감 기한 : 2025.08.17.(일요일)
> 🔥 제출일 : 2025.08.17.(일요일)
- [BOJ] 양 한마리... 양 두마리... / 실버2 / 11분 ✨
=> [2025년 8월 둘째주 / ahma0] DFS/BFS

youbbin/PGS_49189.cs
> 🗓️ 마감 기한 : 2025.08.24.(일)
> 🔥 제출일 : 2025.08.22.(금)
- [PGS] 가장 먼 노드 / Lv3 / 40분 ✨
=> [2025년 8월 셋째주/youbbin] 그래프 이론

ahma0/BOJ_5567.java
> 🗓️ 마감 기한 : 2025.08.24.(일)
> 🔥 제출일 : 2025.08.24.(일)
- [BOJ] 결혼식 / 실버2 / 20분 ✨
=> [2025년 8월 셋째주 / ahma0] 그래프 이론

chaeryeon823/BOJ_11403.py
> 🗓️ 마감 기한 : 2025.08.24.(일요일)
> 🔥 제출일 : 2025.08.24.(일요일)
- [BOJ] 경로찾기 / S1 ✨
=> [2025년 8월 셋째주 / chaeryeon823] 그래프 이론

jiyoung1814/boj_17182_police_checkpoint.py
> 🗓️ 마감 기한 : 2025.08.31
> 🔥 제출일 : 2025.08.30
- [BOJ] 도로 검문/ 골드 1 / 30분 ✨
=> [2025년 8월 넷째주/jiyoung1814] 아무거나

chaeryeon823/BOJ_1158.js
> 🗓️ 마감 기한 : 2025.08.31.(일요일)
> 🔥 제출일 : 2025.08.31.(일요일)
- [BOJ] 요세푸스 문제 / S4 ✨
=> [2025년 8월 넷째주/chaeryeon823] 아무거나

hh830/BOJ_2491.java
> 🗓️ 마감 기한 : 2025.09.07.(일)
> 🔥 제출일 : 2025.09.07.(일)
- [BOJ] 수열 / 실버4 / 30분 ✨
=> [2025년 9월 첫째주/hh830] 다이나믹 프로그래밍

chaeryeon823/BOJ_1010.js
> 🗓️ 마감 기한 : 2025.09.07.(일)
> 🔥 제출일 : 2025.09.07.(일)
> ⭐️ 주제 문제 풀이 : ⭕️ / ❌
- [BOJ] 다리 놓기 / S5 ✨
=> [2025년 9월 첫째주/chaeryeon823] 다이나믹 프로그래밍

ahma0/BOJ_9507.java
> 🗓️ 마감 기한 : 2025.09.07.(일)
> 🔥 제출일 : 2025.09.07.(일)
- [BOJ] Generations of Tribbles / 실버4 / 8분 ✨
=> [2025년 9월 첫째주 / ahma0] 다이나믹 프로그래밍

hh830/BOJ_2217.java
> 🗓️ 마감 기한 : 2025.09.14.(일)
> 🔥 제출일 : 2025.09.14.(일)
- [BOJ] 로프 / 실버4 / 15분 ✨
=> [2025년 9월 둘째주/hh830] 다이나믹 프로그래밍

chaeryeon823/BOJ_1427.js
> 🗓️ 마감 기한 : 2025.09.14.(일요일)
> 🔥 제출일 : 2025.09.14.(일요일)
- [BOJ] 소트인사이드 / S5 ✨
=> [2025년 9월 둘째주/chaeryeon823] 정렬

julia8024/BOJ_2910.py
> 🗓️ 마감 기한 : 2025.09.14.(일)
> 🔥 제출일 : 2025.09.14.(일)
- [BOJ] 빈도 정렬 / 실버3 / 30분 ✨
(✨ : 정렬 문제)
=> [2025년 9월 둘째주 / julia8024] 정렬

youbbin/BOJ_2512.py
> 🗓️ 마감 기한 : 2025.09.21.(일)
> 🔥 제출일 : 2025.09.18.(목)
- [BOJ] 예산 / 실버2 / 30분 ✨
=> [2025년 9월 셋째주 / youbbin] 이진탐색

hh830/BOJ_2776.java
> 🗓️ 마감 기한 : 2025.09.21.(일)
> 🔥 제출일 : 2025.09.21.(일)
- [BOJ] 암기왕 / 실버4 / 10분 ✨
=> [2025년 09월 셋째주 / hh830] 이진탐색

jiyoung1814/boj_implementation_ZOAC.py
> 🗓️ 마감 기한 : 2025.09.28.
> 🔥 제출일 : 2025.09.28.
- [BOJ] ZOAC/ 골드 5/ 40분 ✨
=> [2025년 09월 넷째주 / jiyoung1814] 구현

julia8024/LTC_179.py, julia8024/LTC_55.py
> 🗓️ 마감 기한 : 2025.10.05.(일)
> 🔥 제출일 : 2025.10.04.(토)
- [LTC] Jump Game / Medium / 20분 ✨
- [LTC] Largest Number / Medium / 20분
(✨ : 그리디 문제)
=> [2025년 10월 첫째주 / julia8024] 그리디

ahma0/BOJ_10610.java, ahma0/BOJ_1966.java
> 🗓️ 마감 기한 : 2025.10.05.(일)
> 🔥 제출일 : 2025.10.05.(일)
- [BOJ] 프린터큐 / 실버3 / 20분
- [BOJ] 30 / 실버4 / 10분 ✨
=> [2025년 10월 첫째주 / ahma0] 그리디
